import SerialCom

print("Starting com test:")
print("Talking to 1: ")
SerialCom.send1("g")
SerialCom.read1()
print("Talking to 2: ")
SerialCom.send2("g")
SerialCom.read2()
print("Talking to 1: ")
SerialCom.send1("g")
SerialCom.read1()
print("Talking to 2: ")
SerialCom.send2("g")
SerialCom.read2()
print("Talking to 1: ")
SerialCom.send1("g")
SerialCom.read1()
print("Talking to 2: ")
SerialCom.send2("g")
SerialCom.read2()
print("Talking to 1: ")
SerialCom.send1("g")
SerialCom.read1()
print("Talking to 2: ")
SerialCom.send2("g")
SerialCom.read2()
print("Test Done")